name: AOV Event Monitor

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write # Cần thiết để lưu history.json
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Lấy toàn bộ lịch sử để push log không bị lỗi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests playwright
          # Lưu ý: Không install browser ở đây để tiết kiệm thời gian. 
          # Script sẽ tự install khi thấy status 200.
          npx playwright install-deps chromium

      - name: Run Monitor
        env:
          EVENT_URL: ${{ secrets.EVENT_URL }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python monitor.py
